#spring.application.name=demo
#spring.security.user.name=admin
#spring.security.user.password=123456
#spring.jpa.hibernate.ddl-auto=none


#update: Cria as tabelas caso elas não existam e atualiza a estrutura se você adicionar novas colunas. 
    #(Não deleta colunas antigas).

#create: Sempre cria as tabelas ao iniciar, mas deleta as tabelas existentes primeiro (cuidado, você perde os dados).

#create-drop: Cria as tabelas e as deleta assim que a aplicação for encerrada.

#validate: Apenas valida se as tabelas já existem e se batem com a sua classe @Entity. 
#Se não existirem, o sistema joga um erro e não inicia.

#none: Não faz nada. É o padrão para ambientes de produção.
